set positional-arguments

# Display help
help:
    just -l

# `openx`
openx *args:
    cargo run --bin openx -- "$@"

# `openx exec`
exec *args:
    cargo run --bin openx -- exec "$@"

# `openx tui`
tui *args:
    cargo run --bin openx -- tui "$@"

# Run the CLI version of the file-search crate.
file-search *args:
    cargo run --bin openx-file-search -- "$@"

# format code
fmt:
    cargo fmt -- --config imports_granularity=Item

fix *args:
    cargo clippy --fix --all-features --tests --allow-dirty "$@"

install:
    rustup show active-toolchain
    cargo fetch

# Run the MCP server
mcp-server-run *args:
    cargo run -p openx-mcp-server -- "$@"
